# Copyright 2010-2011 Andrea Nall
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env')
env.Append( CPPPATH = ['..'] )

files = [

'Cell.cc',
'CellSet.cc',
'CloneHelper.cc',

'exception/Exception.cc',
'exception/InvalidCellValue.cc',
'exception/InvalidLayout.cc',
'exception/OutOfRange.cc',
'exception/PuzzleSizeMismatch.cc',

'plugin/cell/EvenOdd.cc',
'plugin/Cell.cc',
'plugin/puzzle/Diagonal.cc',
'plugin/Puzzle.cc',
'plugin/square/Irregular.cc',
'plugin/square/Standard.cc',
'plugin/Square.cc',

'Position.cc',
'Puzzle.cc',
'Solver.cc',

];

Import('rdata')

rdata['lib'] = env.StaticLibrary('../../sudoku', files )